import Image from 'next/image'
import Head from 'next/head'
import Hero from '@/components/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <title>Photography Next App</title>
      </Head>
      <Hero heading="Captur Photography" message="I capture moments in nature and keep them alive." />
    </div>
  )
}
