import Image from 'next/image'
import Head from 'next/head'
import Hero from '@/components/Hero'
import Slider from '@/components/Slider'
import { SliderData } from '@/components/SliderData'
import Instagram from '@/components/Instagram'

export default function Home() {
  return (
    <div>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <title>Photography Next App</title>
      </Head>
      <Hero heading="Andrea Photography" message="Catturo momenti nella natura e li mantengo vivi." />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  )
}
